name: notice_manager
description: "경영학전공 공지 생성기"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  calendar_date_picker2: ^1.1.8
  dio: ^5.7.0
  equatable: ^2.0.5
  file_picker: ^8.3.1
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  go_router: ^14.3.0
  http_parser: ^4.0.2
  image_picker: ^1.1.1
  image_picker_for_web: ^3.0.6
  intl: ^0.20.2
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: fonts/Pretendard-Light.ttf
          weight: 300
        - asset: fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: fonts/Pretendard-Black.ttf
          weight: 900
